name: verify

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    #- name: Set up Python
    #  uses: actions/setup-python@v4

   # - name: Install dependencies
   #   run: pip3 install -U git+https://github.com/${{ github.repository }}.git@main

    # required only if you want to verify Java code
    - name: Install dependencies (Java)
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '11'

    - name: Run tests
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        YUKICODER_TOKEN: ${{ secrets.YUKICODER_TOKEN }}
        GH_PAT: ${{ secrets.GH_PAT }}
      run: oj-verify all
